version: '3.2'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api.insecure=true --providers.docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8082:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  redisinsight:
    image: redislabs/redisinsight:latest
    ports: 
      - 8002:8001
  
  mongo:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - data_mongo:/data/db
    labels:
      - "traefik.frontend.rule=Host:mongo.docker.localhost"
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo:mongo
    labels:
      - "traefik.frontend.rule=Host:express.docker.localhost"
    
volumes:
  data_mongo:
