name: Production
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::$(git rev-parse --short HEAD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CVCIO_CONTAINER_REGISTRY }}
          username: ${{ secrets.CVCIO_CLIENT_ID }}
          password: ${{ secrets.CVCIO_CLIENT_SECRET }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.1.0
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ${{ secrets.CVCIO_CONTAINER_REGISTRY }}/covid-19-api:${{ steps.vars.outputs.tag }}
            ${{ secrets.CVCIO_CONTAINER_REGISTRY }}/covid-19-api:latest
